void glutGameInit();
void glutGameMainLoop();
void glutGameIdle();
void glutGameSystickService(unsigned int systick_old);
unsigned int glutGameSystickGet();
void glutGameRenderSceneSet(void (*fnc_p)());
void glutGameRender2DSceneSet(void (*fnc_p)());
void glutGameRenderScene();
void glutGameRender2DScene();
void glutGameRender();
void glutGameRescale(GLint n_w, GLint n_h);
void glutGameRenderFPS();
double glutGameRenderGetFPS();
void glutGameCameraInit(double x, double y, double z);
void glutGameCameraRender();
void glutGameCameraPlace(double x, double y, double z, double rotation_xz, double rotation_y);
void glutGameControlInit();
void glutGameControlUpdate();
void glutGameMouseInit();
void glutGameMouseKeys(int button, int state, int x, int y);
void glutGameMouseMove(int x, int y);
void glutGameKeyboardInit();
void glutGameKeyboardPressed(int key, int x, int y);
void glutGameKeyboardReleased(int key, int x, int y);
void glutGameMoveCamera(int key);
void glutGameRotateCamera(double dxa, double dya);
void glutGameRenderLocalAxis();
void glutGameRenderOnScreenInfo();

